title: Deepak Yadav
description: Just a beginning of my writing.

url: https://deepak7376.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: Projects
      url: /projects
    - title: Resume
      url: /resume
    # - title: Blog Categories
    #    url: /blog-categories
    - title: About
      url: /about
    - title: Contact
      url: /contact


social:
    github: deepak7376
    twitter: ydeepak92
    email: dky.united@gmail.com
    linkedin: dky7376

google_analytics: "UA-58263416-1"

disqus:
    shortname: deepak7376
